# Publish dependencies to NPM on release
# https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish packages on release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org/"
      - run: npm publish ./common/core --access public
      - run: npm publish ./themes/bootstrap --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
